---
title: "02_planning"
output: html_document
date: "2023-04-23"
---

<<<<<<< HEAD
```{r}
# install.packages("gggantt")
install.packages("plan")
library(tidyverse)
library(ggplot2)
library(plan)
# library(gggantt)
```


Some ideas for gantt chart:
https://www.molecularecologist.com/2019/01/03/simple-gantt-charts-in-r-with-ggplot2-and-the-tidyverse/
https://jtr13.github.io/cc19/gantt-charts.html
https://stackoverflow.com/questions/3550341/gantt-charts-with-r

Create empty df
```{r}
proj_plan_data <- data.frame(matrix(ncol = 5, nrow = 0))
colnames(proj_plan_data) <- c("Item", "Activity", "Type_of_activity", "Start", "End")
proj_plan_data$Item <- as.numeric(proj_plan_data$Item)
proj_plan_data$Activity <- as.character(proj_plan_data$Activity)
proj_plan_data$Type_of_activity <- as.character(proj_plan_data$Type_of_activity)
proj_plan_data$Start <- as.Date(proj_plan_data$Start)
proj_plan_data$End <- as.Date(proj_plan_data$End)
```

Add activities
```{r}
proj_plan_data <- rbind(proj_plan_data, data.frame(
  "item" = 1,
  "Activity" = "Adding country codes",
  "Type_of_activity" = "Data manipulation",
  "Start" = as.Date("2023-04-23"),
  "End" = as.Date("2023-05-23")))

proj_plan_data <- rbind(proj_plan_data, data.frame(
  "item" = 2,
  "Activity" = "Creating Gantt chart for blacklisted countries",
  "Type_of_activity" = "Visualisaton",
  "Start" = as.Date("2023-05-10"),
  "End" = as.Date("2023-06-23")))

proj_plan_data <- rbind(proj_plan_data, data.frame(
  "item" = 3,
  "Activity" = "Descriptive statistics",
  "Type_of_activity" = "Visualisaton",
  "Start" = as.Date("2023-05-10"),
  "End" = as.Date("2023-09-23")))
  
```

<!-- DF needs to be changed - dates should be in one column, but start or end - in another. Does it mean duplication? -->

```{r}
# g.proj_plan_data <- proj_plan_data %>% 
#   pivot_longer(4:5,
#                names_to = "State",
#                values_to = "Date")
# 
# g.proj_plan_data$Date <- as.Date(g.proj_plan_data$Date)
```

```{r}
tidy_proj_plan_data <- proj_plan_data %>% 
  gather(key=started_ended, value = date, -item, -Activity, -Type_of_activity) %>% 
  arrange(item)
```


Project limeline
```{r}
ggplot() +
  geom_line(data = tidy_proj_plan_data, aes(x = Activity, y = date, color = Type_of_activity), size = 10) +
  coord_flip()
```

```{r}
ggplot() +
  geom_line(data = tidy_proj_plan_data, mapping = aes(x = fct_rev(fct_inorder(Activity)), y = date, color = Type_of_activity), size = 10) +
  coord_flip()
```





>>>>>>> 30344447130f6e6b22e8395bd58353d805a07237
